Report nice message on datetime errors
One of the quite common errors are bad datetimes in Origin -
CREATION-TIME, like datetime(1990, 0, 0, 0, 0, 0, 0).
In Python 3.5 such dates are created just fine.
Starting from Python 3.6 some date checks are introduced and creation of
such dates fails.

However, message from attribute.value is not very useful:
When attempting to retrieve attribute we get
TypeError: Unable to convert function return value to a Python type!

This commit ensures that default python datetime message is printed.
Unfortunately, from this message it won't be clear for the user what
numbers were used to create incorrect date.

Decision was made not to attempt adjusting this message, mostly because
it doesn't seem to be worth hacking the way pybind deals with error
messages from Python C API [1].

[1]
https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html#handling-python-exceptions-cpp